# -*- coding: utf-8 -*-
"""Aula02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/163QRmra2LrVPGtUFT1ZXLaenpQTE0WdO
"""

#Estrutura condicional 
resposta = input('Deseja ir a próxima tela? ')
if resposta == 'sim' or resposta == 'Sim':
    print('Você foi para outra tela')
else:
    print('Você saiu do sistema')

#Estrutura condicional
nome = input('Informe o nome de usuário: ')
sexo = input("Informe 'F' para feminino e 'M para masculino': ").upper()
if (sexo) == 'M':
    sexo = 'o'
elif (sexo == 'F'):
    sexo = 'a'
usuario = int(input('Informe o tipo de usuário \n 1 - para administrador \n 2 - para usuário comum \n 3 - para membro associado '))
if (usuario == 1):
    usuario = 'Administrador do sistema'
elif (usuario == 3):
    usuario = 'Membro associado'
elif (usuario == 2):
    usuario = 'Usuário comum'
else:
    usuario = 'Não existente'
print(f'Seja bem vind{sexo} {nome}, a sua licença é de {usuario}')